name = "swc-forecast-TWAI-23a"
uuid = "dde34a52-6d0c-4411-ba34-775de8d37d08"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
