
name: install-julia-print-hello
on: [push]
jobs:
  install-julia:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.6.7
    - name: Print message and execute a julia script
      run: | # this allows multi-line execution
          julia -e 'println("This is julia $(VERSION)")'
          julia -e 'println("Does it work on a branch besides master?"); println("Yes, it works!");'
          julia -e 'println("Current directory of julia: $(pwd())")'
          echo "GITHUB_WORKSPACE" ${GITHUB_WORKSPACE}
          echo "GITHUB_ACTION_REPOSITORY" ${GITHUB_ACTION_REPOSITORY}
          echo "GITHUB_PATH" ${GITHUB_PATH}
# julia -e 'include("script/github_actions/julia_script.jl")'
# julia -e 'lineplot([-1, 2, 3, 7], [-1, 2, 9, 4])'
